# Generated by Django 2.2.24 on 2021-11-19 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_tripreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='likes',
            field=models.ManyToManyField(related_name='story_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
