# Generated by Django 2.2.24 on 2021-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_like_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='storyowner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
